apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-xjvx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nuvn-tenant/rhtap-demo-app/hacbs-test-project-xjvx@sha256:f64cceca20044f4256f5a4b2ca9a9b6a21b640b69e9bdd87c8eea45581527eac
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
