apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-xjvx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-xjvx
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-xjvx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-xjvx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-xjvx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nuvn-tenant/rhtap-demo-app/hacbs-test-project-xjvx@sha256:f64cceca20044f4256f5a4b2ca9a9b6a21b640b69e9bdd87c8eea45581527eac
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
